# version: "3.7"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
    environment:
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
      # - SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY}
    volumes:
      - ..:/workspace
    ports:
      - 5173:5173
    command:
      - /bin/sh
